INSERT INTO TODO_SERIE (TSE_ID,TSE_SERIE_TITLE, TSE_SERIE_COMPLETED ) VALUES (1,'Friends', false);
INSERT INTO TODO_SERIE (TSE_ID,TSE_SERIE_TITLE, TSE_SERIE_COMPLETED ) VALUES (2,'Frasier', false);

INSERT INTO TODO_SEASON (TSN_SEASON_NUMBER,TSN_YEAR, TSN_COMPLETED,TSE_ID  ) VALUES (1,1994,true,1);


INSERT INTO TODO_SEASON (TSN_SEASON_NUMBER,TSN_YEAR, TSN_COMPLETED,TSE_ID  ) VALUES (1,1994,true,2);



INSERT INTO TODO_EPISODE (TEP_EPISODE_NUMBER,TEP_EPISODE_TITLE, TEP_WATCHED,TEP_RATING,TSN_ID  ) VALUES (1,'the one were', true, 8,1);
INSERT INTO TODO_EPISODE (TEP_EPISODE_NUMBER,TEP_EPISODE_TITLE, TEP_WATCHED,TEP_RATING,TSN_ID  ) VALUES (2,'the one were', true, 8,1);
INSERT INTO TODO_EPISODE (TEP_EPISODE_NUMBER,TEP_EPISODE_TITLE, TEP_WATCHED,TEP_RATING ,TSN_ID ) VALUES (3,'the one were', true, 8,1);
INSERT INTO TODO_EPISODE (TEP_EPISODE_NUMBER,TEP_EPISODE_TITLE, TEP_WATCHED,TEP_RATING ,TSN_ID ) VALUES (4,'the one were', true, 8,1);
INSERT INTO TODO_EPISODE (TEP_EPISODE_NUMBER,TEP_EPISODE_TITLE, TEP_WATCHED,TEP_RATING ,TSN_ID ) VALUES (5,'the one were', true, 8,1);
INSERT INTO TODO_EPISODE (TEP_EPISODE_NUMBER,TEP_EPISODE_TITLE, TEP_WATCHED,TEP_RATING  ,TSN_ID) VALUES (6,'the one were', true, 8,1);
INSERT INTO TODO_EPISODE (TEP_EPISODE_NUMBER,TEP_EPISODE_TITLE, TEP_WATCHED,TEP_RATING  ,TSN_ID) VALUES (7,'the one were', true, 8,1);
INSERT INTO TODO_EPISODE (TEP_EPISODE_NUMBER,TEP_EPISODE_TITLE, TEP_WATCHED,TEP_RATING,TSN_ID  ) VALUES (8,'the one were', true, 8,1);
INSERT INTO TODO_EPISODE (TEP_EPISODE_NUMBER,TEP_EPISODE_TITLE, TEP_WATCHED,TSN_ID  ) VALUES (9,'the one were', false, 1);
INSERT INTO TODO_EPISODE (TEP_EPISODE_NUMBER,TEP_EPISODE_TITLE, TEP_WATCHED,TSN_ID  ) VALUES (10,'the one were', false, 1);
INSERT INTO TODO_EPISODE (TEP_EPISODE_NUMBER,TEP_EPISODE_TITLE, TEP_WATCHED,TSN_ID  ) VALUES (11,'the one were', false, 1);
INSERT INTO TODO_EPISODE (TEP_EPISODE_NUMBER,TEP_EPISODE_TITLE, TEP_WATCHED,TSN_ID  ) VALUES (12,'the one were', false, 1);
INSERT INTO TODO_EPISODE (TEP_EPISODE_NUMBER,TEP_EPISODE_TITLE, TEP_WATCHED,TSN_ID  ) VALUES (13,'the one were', false, 1);
INSERT INTO TODO_EPISODE (TEP_EPISODE_NUMBER,TEP_EPISODE_TITLE, TEP_WATCHED,TSN_ID  ) VALUES (14,'the one were', false, 1);
INSERT INTO TODO_EPISODE (TEP_EPISODE_NUMBER,TEP_EPISODE_TITLE, TEP_WATCHED,TSN_ID  ) VALUES (15,'the one were', false, 1);
INSERT INTO TODO_EPISODE (TEP_EPISODE_NUMBER,TEP_EPISODE_TITLE, TEP_WATCHED,TSN_ID  ) VALUES (16,'the one were', false, 1);

INSERT INTO TODO_EPISODE (TEP_EPISODE_NUMBER,TEP_EPISODE_TITLE, TEP_WATCHED,TEP_RATING,TSN_ID  ) VALUES (1,'the one were', true, 8,2);
INSERT INTO TODO_EPISODE (TEP_EPISODE_NUMBER,TEP_EPISODE_TITLE, TEP_WATCHED,TEP_RATING,TSN_ID  ) VALUES (2,'the one were', true, 8,2);
INSERT INTO TODO_EPISODE (TEP_EPISODE_NUMBER,TEP_EPISODE_TITLE, TEP_WATCHED,TEP_RATING ,TSN_ID ) VALUES (3,'the one were', true, 6,2);
INSERT INTO TODO_EPISODE (TEP_EPISODE_NUMBER,TEP_EPISODE_TITLE, TEP_WATCHED,TEP_RATING ,TSN_ID ) VALUES (4,'the one were', true, 8,2);
INSERT INTO TODO_EPISODE (TEP_EPISODE_NUMBER,TEP_EPISODE_TITLE, TEP_WATCHED,TEP_RATING ,TSN_ID ) VALUES (5,'the one were', true, 3,2);
INSERT INTO TODO_EPISODE (TEP_EPISODE_NUMBER,TEP_EPISODE_TITLE, TEP_WATCHED,TEP_RATING  ,TSN_ID) VALUES (6,'the one were', false, 8,2);
INSERT INTO TODO_EPISODE (TEP_EPISODE_NUMBER,TEP_EPISODE_TITLE, TEP_WATCHED,TEP_RATING  ,TSN_ID) VALUES (7,'the one were', false, 1,2);
INSERT INTO TODO_EPISODE (TEP_EPISODE_NUMBER,TEP_EPISODE_TITLE, TEP_WATCHED,TEP_RATING,TSN_ID  ) VALUES (8,'the one were', false, 8,2);
INSERT INTO TODO_EPISODE (TEP_EPISODE_NUMBER,TEP_EPISODE_TITLE, TEP_WATCHED,TSN_ID  ) VALUES (9,'the one were', false, 2);
INSERT INTO TODO_EPISODE (TEP_EPISODE_NUMBER,TEP_EPISODE_TITLE, TEP_WATCHED,TSN_ID  ) VALUES (10,'the one were', false, 2);
INSERT INTO TODO_EPISODE (TEP_EPISODE_NUMBER,TEP_EPISODE_TITLE, TEP_WATCHED,TSN_ID  ) VALUES (11,'the one were', false, 2);
INSERT INTO TODO_EPISODE (TEP_EPISODE_NUMBER,TEP_EPISODE_TITLE, TEP_WATCHED,TSN_ID  ) VALUES (12,'the one were', false, 2);
INSERT INTO TODO_EPISODE (TEP_EPISODE_NUMBER,TEP_EPISODE_TITLE, TEP_WATCHED,TSN_ID  ) VALUES (13,'the one were', false, 2);
INSERT INTO TODO_EPISODE (TEP_EPISODE_NUMBER,TEP_EPISODE_TITLE, TEP_WATCHED,TSN_ID  ) VALUES (14,'the one were', false, 2);
INSERT INTO TODO_EPISODE (TEP_EPISODE_NUMBER,TEP_EPISODE_TITLE, TEP_WATCHED,TSN_ID  ) VALUES (15,'the one were', false, 2);
INSERT INTO TODO_EPISODE (TEP_EPISODE_NUMBER,TEP_EPISODE_TITLE, TEP_WATCHED,TSN_ID  ) VALUES (16,'the one were', false, 2);
